#include <iostream>
#include <string>
#include <fstream>
#include <streambuf>
#include "runtime.h"

/* This is the function generated by the example: */
struct PtrPair {
  Pointer src;
  Pointer dst;
};
extern PtrPair func_0(Pointer src, Pointer dst);

static std::string readWholeFile(std::string const fname)
{
  std::ifstream t(fname);
  std::string str(std::istreambuf_iterator<char>(t),
                  (std::istreambuf_iterator<char>()));
  return str;
}

int main(int numArgs, char **args)
{
  std::string input =
    readWholeFile(numArgs <= 1 ? "/dev/stdin" : args[1]);
  Pointer src(input);

  while (src.rem() > 0) {
    Size outSz(1024);
    Pointer dst(outSz);

    PtrPair ptrs = func_0(src, dst);

    // Print serialized:
    assert(ptrs.dst.offset < ptrs.dst.size-1);
    ptrs.dst.buffer.get()[ptrs.dst.offset++] = '\0';
    std::cout << ptrs.dst.buffer << '\n';

    src = ptrs.src;
  }

  return 0;
}
