#include <iostream>
#include <string>
#include <fstream>
#include <streambuf>
#include "runtime.h"

/* This is the function generated by the example: */
struct PtrPair {
  Pointer src;
  Pointer dst;
};
extern PtrPair func2_0(Pointer src, Pointer dst);

static std::string readWholeFile(std::string const fname)
{
  std::ifstream t(fname);
  std::string str(std::istreambuf_iterator<char>(t),
                  (std::istreambuf_iterator<char>()));
  return str;
}

int main(int numArgs, char **args)
{
  char const *fname = "/dev/stdin";
  char delim = '\n';

  for (int a = 1; a < numArgs; a++) {
    if (a < numArgs - 1 && (
          0 == strcasecmp(args[a], "--delim") ||
          0 == strcasecmp(args[a], "-d")
        )) {
      delim = args[a+1][0];
    } else {
      fname = args[a];
    }
  }

  std::string input = readWholeFile(fname);
  Pointer src(input);

  while (src.rem() > 0) {
    Size outSz(1024);
    Pointer dst(outSz);

    PtrPair ptrs = func2_0(src, dst);

    // Print serialized:
    assert(ptrs.dst.offset < ptrs.dst.size-1);
    if (ptrs.dst.buffer) {
      fwrite(ptrs.dst.buffer.get(), 1, ptrs.dst.offset, stdout);
      if (delim != '\0') fwrite(&delim, sizeof(delim), 1, stdout);
    } // else it's a heap value

    src = ptrs.src;
  }

  return 0;
}
